GET http://172.24.125.247:28017/WORD-CLOUD/articles/ HTTP/1.1

###

GET http://localhost:27080 HTTP/1.1

###

POST http://localhost:27080/_connect HTTP/1.1
content-type: application/json

{
    "server": "172.24.125.247:27017",
    "username": "root",
    "password": "sisko@7660$boo",
    "authenticationDatabase": "admin",
}
